import { CashierSalesResponse } from "types/pocketbase-types";

interface SelectedValues {
  expenses: number;
  salesByCashier: number;
  salesBySystem: number;
  totalOrdersAmount: number;
  name: string;
}

const useGenerateCashierLog = (originalArray: CashierSalesResponse[]) => {
  const selectedArray: SelectedValues[] = originalArray.map((obj: any) => {
    return {
      expenses: obj.expenses,
      salesByCashier: obj.sales_by_cashier,
      salesBySystem: obj.sales_by_system,
      totalOrdersAmount: obj.total_orders_amount,
      name: obj.expand?.user?.expand?.employee_data?.name || "",
    };
  });

  const headers = [
    { label: "Employee Name", key: "name" },
    { label: "Expenses", key: "expenses" },
    { label: "Sales By Cashier", key: "salesByCashier" },
    { label: "Sales Generated by system", key: "salesBySystem" },
    { label: "Total Orders Amount", key: "totalOrdersAmount" },
  ];

  return { headers, data: selectedArray };
};

export default useGenerateCashierLog;
